version: 2
jobs:
  release:
    working_directory: ~/simple-react-calendar

    docker:
      - image: cypress/browsers:node12.6.0-chrome77

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
            name: Save Yarn Package Cache
            key: yarn-packages-{{ checksum "yarn.lock" }}
            paths:
              - ~/.cache/yarn

      - run:
          name: Build dist
          command: yarn build

      - run:
          name: Build lib
          command: yarn build:lib

      - run:
          name: Build Storybook
          command: yarn storybook:build

      - run:
          name: Release
          command: ./node_modules/.bin/semantic-release

  prCheck:
    working_directory: ~/simple-react-calendar

    docker:
      - image: cypress/browsers:node12.6.0-chrome77

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
            name: Save Yarn Package Cache
            key: yarn-packages-{{ checksum "yarn.lock" }}
            paths:
              - ~/.cache/yarn

      - run:
          name: Danger Check
          command: yarn danger ci

      - run:
          name: Lint ESLint
          command: yarn lint

      - run:
          name: Lint Typescript
          command: yarn lint:tsc

      - run:
          name: Unit test
          command: yarn test:ci

workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            branches:
              only: master

  pr_check:
    jobs:
      - prCheck
